import { Roboto_Serif } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const roboto_serif = Roboto_Serif({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=" bg-backup">
      <body className={roboto_serif.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
