import { Roboto_Serif, Andada_Pro } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthProvider } from "./Providers";
import { Toaster } from "react-hot-toast";

const roboto_serif = Roboto_Serif({ subsets: ["latin"] });
const andada_pro = Andada_Pro({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={roboto_serif.className}>
        <AuthProvider>
          <Navbar />
          <Analytics />
          <Toaster
            position="top-right"
            reverseOrder={false}
            className="absolute"
          />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
